from __future__ import annotations

from collections import Counter
from collections.abc import Iterable
from html import escape

from auditforge.finding import Finding, SEVERITY_ORDER
from auditforge.masking import redact_text


def generate_html(findings: Iterable[Finding]) -> str:
    finding_list = list(findings)
    counts = Counter(finding.severity for finding in finding_list)
    lines: list[str] = [
        "<!doctype html>",
        '<html lang="en">',
        "<head>",
        '  <meta charset="utf-8">',
        "  <title>Security Assessment Report</title>",
        "  <style>",
        "    body { font-family: Arial, sans-serif; line-height: 1.5; margin: 2rem; color: #1f2937; }",
        "    table { border-collapse: collapse; margin: 1rem 0; min-width: 18rem; }",
        "    th, td { border: 1px solid #d1d5db; padding: 0.4rem 0.6rem; text-align: left; }",
        "    th { background: #f3f4f6; }",
        "    pre { background: #f9fafb; border: 1px solid #e5e7eb; padding: 0.8rem; overflow-x: auto; }",
        "    .finding { margin-bottom: 2rem; }",
        "  </style>",
        "</head>",
        "<body>",
        "  <h1>Security Assessment Report</h1>",
        "  <p>Generated by AuditForge.</p>",
        "  <h2>Summary</h2>",
        "  <table>",
        "    <thead><tr><th>Severity</th><th>Count</th></tr></thead>",
        "    <tbody>",
    ]

    for severity in SEVERITY_ORDER:
        lines.append(f"      <tr><td>{severity}</td><td>{counts.get(severity, 0)}</td></tr>")

    lines.extend(["    </tbody>", "  </table>"])

    if not finding_list:
        lines.extend(["  <p>No findings were provided.</p>", "</body>", "</html>"])
        return "\n".join(lines) + "\n"

    for severity in SEVERITY_ORDER:
        severity_findings = [finding for finding in finding_list if finding.severity == severity]
        if not severity_findings:
            continue

        lines.append(f'  <section id="{severity.lower()}">')
        lines.append(f"    <h2>{severity}</h2>")
        for index, finding in enumerate(severity_findings, start=1):
            lines.extend(_render_finding(finding, index))
        lines.append("  </section>")

    lines.extend(["</body>", "</html>"])
    return "\n".join(lines) + "\n"


def _render_finding(finding: Finding, index: int) -> list[str]:
    return [
        '    <article class="finding">',
        f"      <h3>{index}. {_inline(finding.title)}</h3>",
        f"      <p><strong>Affected asset:</strong> {_inline(finding.affected_asset)}</p>",
        "      <h4>Evidence</h4>",
        f"      <pre><code>{_block(finding.evidence)}</code></pre>",
        "      <h4>Impact</h4>",
        f"      <p>{_paragraph(finding.impact)}</p>",
        "      <h4>Recommendation</h4>",
        f"      <p>{_paragraph(finding.recommendation)}</p>",
        "    </article>",
    ]


def _inline(value: object) -> str:
    text = " ".join(redact_text(value).split()) or "Not provided"
    return escape(text, quote=True)


def _paragraph(value: object) -> str:
    text = redact_text(value).strip() or "Not provided"
    return escape(text, quote=True)


def _block(value: object) -> str:
    text = redact_text(value).strip() or "Not provided"
    return escape(text, quote=True)
