from __future__ import annotations

from collections import Counter
from collections.abc import Iterable

from auditforge.finding import Finding, SEVERITY_ORDER
from auditforge.masking import redact_text


def generate_markdown(findings: Iterable[Finding]) -> str:
    finding_list = list(findings)
    lines: list[str] = [
        "# Security Assessment Report",
        "",
        "Generated by AuditForge.",
        "",
        "## Summary",
        "",
        "| Severity | Count |",
        "| --- | ---: |",
    ]

    counts = Counter(finding.severity for finding in finding_list)
    for severity in SEVERITY_ORDER:
        lines.append(f"| {severity} | {counts.get(severity, 0)} |")

    if not finding_list:
        lines.extend(["", "No findings were provided.", ""])
        return "\n".join(lines)

    for severity in SEVERITY_ORDER:
        severity_findings = [finding for finding in finding_list if finding.severity == severity]
        if not severity_findings:
            continue

        lines.extend(["", f"## {severity}", ""])
        for index, finding in enumerate(severity_findings, start=1):
            lines.extend(_render_finding(finding, index))

    return "\n".join(lines).rstrip() + "\n"


def _render_finding(finding: Finding, index: int) -> list[str]:
    return [
        f"### {index}. {_inline(redact_text(finding.title))}",
        "",
        f"- **Affected asset:** {_inline(redact_text(finding.affected_asset))}",
        "",
        "#### Evidence",
        "",
        _code_block(redact_text(finding.evidence)),
        "",
        "#### Impact",
        "",
        _paragraph(redact_text(finding.impact)),
        "",
        "#### Recommendation",
        "",
        _paragraph(redact_text(finding.recommendation)),
        "",
    ]


def _inline(value: str) -> str:
    cleaned = " ".join(value.split())
    return cleaned.replace("|", "\\|") or "Not provided"


def _paragraph(value: str) -> str:
    return value.strip() or "Not provided"


def _code_block(value: str) -> str:
    text = value.strip() or "Not provided"
    fence = "```"
    while fence in text:
        fence += "`"
    return f"{fence}text\n{text}\n{fence}"
